### ISSUE TITLE
Asus UX7602VI non responsive hotkeys

### ISSUE THREAD

**Issue by fch4um0n7** [asus-linux-drivers/asus-wmi-hotkeys-driver#13]
Hello,

I'm desperately trying to get all (or most) of my recently acquired Asus UX7602VI laptop hotkeys to work but so far no luck whatsoever.

The laptop is running Ubuntu 22.04.4 LTS with kernel 6.6.5 and none of the following keys do anything at all:
- brightness up + down (Fn4+5)
- touchpad enable/disable (Fn6)
- keyboard backlit brightness (Fn7)
- microphone enable/disable (Fn9)
- camera enable/disable (Fn10)
- MyAsus (Fn12) - expected

Worst part is even the command `libinput debug-events` does not catch or display anything from those keys (others displaying result as expected).

Brightness can be adjusted via the Settings menu.
Touchpad works but cannot be disabled via hotkey.
Keyboard brightness is off all the time except during boot or under Windows 11.
Microphone works but cannot be disabled via hotkey.
Camera hotkey works but simply does not turn on/off its LED.
Also, unrelated but only 2 out of 4 internal speakers work.

I know this repo is only related to hotkeys but I thought you might have some pointers for the other unrelated issues.

Any idea where to go from here?
Thanks.

**Comment by ldrahnik** [comment]
@FrancoisChaumont 

Hello,

> The laptop is running Ubuntu 22.04.4 LTS with kernel 6.6.5 and none of the following keys do anything at all:..

For the camera, toggling touchpad and microphone script you can look at how I solved these issues [here](https://github.com/ldrahnik/elementary-os-scripts) on Ubuntu 22.04.03 LTS based distro Elementary OS Loki 7.1.

> Camera hotkey works but simply does not turn on/off its LED.

Toggling camera LED, even only LED fix without rebinding key can be solved by this package. More in Readme.md.

> Keyboard backlight brightness up/down

The same as previous, can be fixed also by this driver in case exist file `/sys/class/leds/asus::kbd_backlight/brightness` or similar or you know dev id for `/sys/kernel/debug/asus-nb-wmi`. More in Readme.md.

> MyAsus

The original app MyAsus supports only Windows and replacement for linux does not exist AFAIK.

**Comment by ldrahnik** [comment]
@FrancoisChaumont Does work that joystick or what is that on the left side from the touchpad under Linux?

**Comment by fch4um0n7** [comment]
> @FrancoisChaumont Does work that joystick or what is that on the left side from the touchpad under Linux?

That is called Asus Dial (showcased [here](https://www.asus.com/laptops/for-creators/zenbook/zenbook-pro-16x-oled-ux7602/)) and apparently managed by a software named [ProArt Creator Hub](https://www.asus.com/proart/software-solutions/proart-creator-hub).

And of course it does not work under Linux.

**Comment by ldrahnik** [comment]
@FrancoisChaumont In case that joystick send something `$ sudo libinput debug-events` I could try implement that so feel free to eventually create a discussion in this org as it is off-topic for this driver.

**Comment by ldrahnik** [comment]
@FrancoisChaumont Looks like the keyboard has brightness RGB, I had `GU603ZI` for like 14 days and already exist projects for controlling RGB backlight for linux, I guess I had installed [this one](https://github.com/wroberts/rogauracore)

**Comment by fch4um0n7** [comment]
> @FrancoisChaumont In case that joystick send something `$ sudo libinput debug-events` I could try implement that so feel free to eventually create a discussion in this org as it is off-topic for this driver.

Unfortunately, like the non-functioning hotkeys, nothing is sent to `sudo libinput debug-events`

**Comment by fch4um0n7** [comment]
> @FrancoisChaumont Looks like the keyboard has brightness RGB, I had `GU603ZI` for like 14 days and already exist projects for controlling RGB backlight for linux, I guess I had installed [this one](https://github.com/wroberts/rogauracore)

I actually had tried this already but could not get passed the error message `rogaura keyboard not found`.
I guess this laptop is too new and that repository's last commit dates back 2 years.

**Comment by ldrahnik** [comment]
Can be reopened.

**Comment by fch4um0n7** [comment]
Sorry, I've been swamped these past few days. Nothing seems to work or help so far. Maybe just have to be patient for something to become available...

Anyways, thanks for your help, appreciate it!

**Comment by ldrahnik** [comment]
In case you will send me your `.dsdt` table I can try help you with camera LED toggling by this driver,  touchpad toggling should work with `$ xinput enable/disable`, does not? Also solvable by this driver. With brightness up down I can try help in case you will send me what contains this dir `/sys/class/leds`. Do not give up.

**Comment by fch4um0n7** [comment]
Sweet! 

Here's what I got:
[sys-class-leds.txt](https://github.com/asus-linux-drivers/asus-wmi-hotkeys-driver/files/14762177/sys-class-leds.txt)
[dsdt.log](https://github.com/asus-linux-drivers/asus-wmi-hotkeys-driver/files/14762183/dsdt.log)

Let me know if you need anything else.

**Comment by ldrahnik** [comment]
@FrancoisChaumont Did you try toggle touchpad using `$ xinput enable/ disable?`

**Comment by ldrahnik** [comment]
@FrancoisChaumont For exporting DSDT table you can follow this:

```
$ sudo apt-get install iasl
$ cp /sys/firmware/acpi/tables/DSDT DSDT
$ sudo iasl -d DSDT
$ cat DSDT.dsl
```

**Comment by fch4um0n7** [comment]
> @FrancoisChaumont Did you try toggle touchpad using `$ xinput enable/ disable?`

I got a warning: `WARNING: running xinput against an Xwayland server`

**Comment by fch4um0n7** [comment]
> @FrancoisChaumont For exporting DSDT table you can follow this:
> 
> ```
> $ sudo apt-get install iasl
> $ cp /sys/firmware/acpi/tables/DSDT DSDT
> $ sudo iasl -d DSDT
> $ cat DSDT.dsl
> ```

`sudo iasl -d DSDT`

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200925
Copyright (c) 2000 - 2020 Intel Corporation

File appears to be binary: found 206113 non-ASCII characters, disassembling
Binary file appears to be a valid ACPI table, disassembling
Input file DSDT, Length 0x96E9F (618143) bytes
ACPI: DSDT 0x0000000000000000 096E9F (v02 _ASUS_ Notebook 01072009 INTL 20200717)
Pass 1 parse of [DSDT]
Pass 2 parse of [DSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)

Parsing completed
Disassembly completed
ASL Output:    DSDT.dsl - 4357653 bytes

 iASL Warning: There were 222 external control methods found during
 disassembly, but only 478 were resolved (4294967040 unresolved). Additional
 ACPI tables may be required to properly disassemble the code. This
 resulting disassembler output file may not compile because the
 disassembler did not know how many arguments to assign to the
 unresolved methods. Note: SSDTs can be dynamically loaded at
 runtime and may or may not be available via the host OS.

 To specify the tables needed to resolve external control method
 references, the -e option can be used to specify the filenames.
 Example iASL invocations:
     iasl -e ssdt1.aml ssdt2.aml ssdt3.aml -d dsdt.aml
     iasl -e dsdt.aml ssdt2.aml -d ssdt1.aml
     iasl -e ssdt*.aml -d dsdt.aml

 In addition, the -fe option can be used to specify a file containing
 control method external declarations with the associated method
 argument counts. Each line of the file must be of the form:
     External (<method pathname>, MethodObj, <argument count>)
 Invocation:
     iasl -fe refs.txt -d dsdt.aml

[DSDT.dsl.gz](https://github.com/asus-linux-drivers/asus-wmi-hotkeys-driver/files/14775737/DSDT.dsl.gz)

**Comment by ldrahnik** [comment]
@FrancoisChaumont This approach should work for your micmute LED (LED on, then LED off):

```
$ sudo -s
$ cd /sys/kernel/debug/asus-nb-wmi
$ echo "0x00040017" > dev_id
$ echo "1" > ctrl_param
$ cat  devs
$ echo "0" > ctrl_param
$ cat  devs
```

Now replace device id with addresses from your dsdt table and check by eyes your camera LED. IMHO what I would try be you are these addresses:


```
$ echo "0x00060078" > dev_id
$ echo "0x00060076" > dev_id
```

Let me know.

**Comment by ldrahnik** [comment]
@FrancoisChaumont For touchpad toggling should work also:

```
$ gsettings set org.gnome.desktop.peripherals.touchpad send-events disabled
$ gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled
```

**Comment by fch4um0n7** [comment]
> @FrancoisChaumont For touchpad toggling should work also:
> 
> ```
> $ gsettings set org.gnome.desktop.peripherals.touchpad send-events disabled
> $ gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled
> ```

Perfect, this works!

**Comment by ldrahnik** [comment]
@FrancoisChaumont Did you try LED?

**Comment by fch4um0n7** [comment]
> @FrancoisChaumont This approach should work for your micmute LED (LED on, then LED off):
> 
> ```
> $ sudo -s
> $ cd /sys/kernel/debug/asus-nb-wmi
> $ echo "0x00040017" > dev_id
> $ echo "1" > ctrl_param
> $ cat  devs
> $ echo "0" > ctrl_param
> $ cat  devs
> ```
> 
> Now replace device id with addresses from your dsdt table and check by eyes your camera LED. IMHO what I would try be you are these addresses:
> 
> ```
> $ echo "0x00060078" > dev_id
> $ echo "0x00060076" > dev_id
> ```
> 
> Let me know.

`0x00040017` is the correct value for micmute LED.

Neither `0x00060078` nor `0x00060076` work for camera. Tried a few others but no success.

**Comment by ldrahnik** [comment]
@FrancoisChaumont Than I do not know, I am sorry. I'd like to hear anything you come up with. Can be reopened in case it will be related to this driver in any way.
